package com.j2ee.db.j2ee_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE AdherentBase PLEASE EDIT ../Adherent.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Adherent object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.j2ee.db.j2ee_db.entity.Adherent;

public class AdherentBase implements RowMapper<Adherent>{
	
	private Long _id;
	
	// Attributes
    private String email;
    private String name;
    private Double phone;
	
	
	
	@Override
	public Adherent mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Adherent obj = new Adherent();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setEmail(rs.getString("email"));
			obj.setName(rs.getString("name"));
			obj.setPhone(rs.getDouble("phone"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}
	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}
	public Double getPhone() {
		return phone;
	}


	public void setPhone(Double phone) {
		this.phone = phone;
	}
	
    
    
    
    
}