package com.j2ee.db.j2ee_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE PretBase PLEASE EDIT ../Pret.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Pret object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.j2ee.db.j2ee_db.entity.Pret;

public class PretBase implements RowMapper<Pret>{
	
	private Long _id;
	
	// Attributes
    private Date date;
    private Date date_retour;
    private Double id_adherent;
    private Double id_livre;
	
	// Relations adherent_pret
	private String adherent_pret;
	
	// Relations livre_pret
	private String livre_pret;
	
	
	
	@Override
	public Pret mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Pret obj = new Pret();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setDate(rs.getDate("date"));
			obj.setDate_retour(rs.getDate("date_retour"));
			obj.setId_adherent(rs.getDouble("id_adherent"));
			obj.setId_livre(rs.getDouble("id_livre"));
			
        	
        	// Relations 1:m adherent_pret
			obj.setAdherent_pret(rs.getString("adherent_pret"));
        	
        	// Relations 1:m livre_pret
			obj.setLivre_pret(rs.getString("livre_pret"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Date getDate() {
		return date;
	}


	public void setDate(Date date) {
		this.date = date;
	}
	public Date getDate_retour() {
		return date_retour;
	}


	public void setDate_retour(Date date_retour) {
		this.date_retour = date_retour;
	}
	public Double getId_adherent() {
		return id_adherent;
	}


	public void setId_adherent(Double id_adherent) {
		this.id_adherent = id_adherent;
	}
	public Double getId_livre() {
		return id_livre;
	}


	public void setId_livre(Double id_livre) {
		this.id_livre = id_livre;
	}
	
    
    // Relations 1:m adherent_pret
	public String getAdherent_pret() {
		return adherent_pret;
	}

	public void setAdherent_pret(String adherent_pret) {
		this.adherent_pret = adherent_pret;
	}
    
    // Relations 1:m livre_pret
	public String getLivre_pret() {
		return livre_pret;
	}

	public void setLivre_pret(String livre_pret) {
		this.livre_pret = livre_pret;
	}
    
    
    
    
}